/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2017-10-23 20:18:31 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.1
 * $ schemats generate -c postgres://username:password@localhost/postgres -t tokens -t token_types -s transcript
 *
 */


export namespace tokensFields {
    export type id = number;
    export type word = string | null;
    export type token_type_id = number | null;
    export type number_of_grapes = number | null;

}

export interface tokens {
    id: tokensFields.id;
    word: tokensFields.word;
    token_type_id: tokensFields.token_type_id;
    number_of_grapes: tokensFields.number_of_grapes;

}

export namespace token_typesFields {
    export type token_type_id = number;
    export type token_type_name = string | null;

}

export interface token_types {
    token_type_id: token_typesFields.token_type_id;
    token_type_name: token_typesFields.token_type_name;

}
